### ISSUE TITLE
How to use dmesh to reduce poly count?

### ISSUE THREAD

**Issue by mrtpk** [SonSang/dmesh#11]
Hi @SonSang,

Thank you for sharing your amazing work. I'm a novice in this field and is learning things through trail and error. With your guides on installation and well written readme, I was able to install `dmesh` and run the example.

Can you guide me on how to reduce poly count (number of faces as shown in Blender) of the attached file? Can you walk me through an example on how to do this? I'm not very sure on the different stages in the experiment (exp1, exp2, exp3). Your help is very much appreciated and I'm looking forward to your response.

Thanks,
Thomas.
[crab.zip](https://drive.google.com/file/d/1SDva6Zmm3W66wIg_lcg3OE_NFTqUuFJf/view?usp=sharing)

**Comment by SonSang** [comment]
Hi Thomas,

Thank you for the interest in my work. If you want to reduce the number of faces in your original mesh, one way could be put it in the point cloud reconstruction algorithm (exp2). It automatically samples points and normals from your mesh, and optimize DMesh to fit the mesh. In doing that, you can change the weight of the `weight_regularizer_coef` as shown [here](https://github.com/SonSang/dmesh/blob/8a76623aa9d8b0cc9673061eb0eef7de36b3d795/exp/config/exp_2/deepfashion3d/164.yaml#L14). This term is related to the number of faces in the final result. As it becomes larger, the algorithm reduces more faces. However, please note that our method does not guarantee manifold mesh for now -- you need post processing to get a clean mesh.

**Comment by mrtpk** [comment]
Thank you very much for getting back to me so quickly. I will try exp2 today. I will post the results once I have them. Since you have already answered my question, I will close this issue. I really appreciate your help and advice. Thanks.
