### ISSUE TITLE
Can only run example codes on cuda 0

### ISSUE THREAD

**Issue by Foreverinne** [SonSang/dmesh#14]
Awesome work!!
When I do not set the device in exp/config/exp_{}/{}.yaml and project/dmesh/exp/recon.py to "cuda:0", there will be an error message 
"Traceback (most recent call last):
  File "/data/ahjiang/project/dmesh/exp/1_mesh_to_dmesh.py", line 566, in <module>
    optimizer.optimize(num_step,
  File "/data/ahjiang/project/dmesh/exp/1_mesh_to_dmesh.py", line 322, in optimize
    pd = PDStruct.forward(points, wdt_result.tets_point_id)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/ahjiang/project/dmesh/diffdt/pd.py", line 157, in forward
    result.pd_vertices = PDStruct.construct_pd_vertices(points, 
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/ahjiang/project/dmesh/diffdt/pd.py", line 196, in construct_pd_vertices
    pdv.positions = PDVertexComputationLayer.apply(points.positions, points.weights, tets_point_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/ahjiang/anaconda3/envs/dmgs/lib/python3.11/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/ahjiang/project/dmesh/diffdt/pd.py", line 22, in forward
    return **d_cc.to(dtype=dtype)**
           ^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.”

I checked the device where **d_cc** is located and found that it is consistent with the device value I set.

**Comment by SonSang** [comment]
Hi, sorry for the late reply.

Our code does not support multi-gpu optimization. If you want to use other GPU than `cuda:0`, I recommend to use `CUDA_VISIBLE_DEVICES={gpu index}` command, then it would only use that single gpu. However, if you want to run the code without it, you can set the active device using `torch.cuda.set_device` command right after you set the device you want to use.

Please let me know if it answers your question.

**Comment by Foreverinne** [comment]
Thanks for your reply.
I have checked `CUDA_VISIBLE_DEVICES={gpu index}` or `torch.cuda.set_device` but they still don't work. 
This error always occurs in the `PDVertexComputationLayer.forward() `function in `dmesh/diffdt/pd.py`. 
```
    def forward(ctx, positions, weights, vertex_point_id):
        dtype = positions.dtype
        d_positions = positions.to(dtype=th.float64)
        d_weights = weights.to(dtype=th.float64)

        d_cc, d_cc_unnorm = _C.compute_circumcenters(d_positions, d_weights, vertex_point_id)
        ctx.save_for_backward(d_positions, d_weights, vertex_point_id, d_cc_unnorm)       
        print('device:{},dtype:{},layout:{},version:{}'.format(d_cc.device,d_cc.dtype,d_cc.layout,th.__version__))
        print(d_cc)
        return d_cc.to(dtype=dtype)
```

I can print the tensor attribute of `d_cc`, but if I print `d_cc` directly, I will get `CUDA error: an illegal memory access was encountered`.
**This error only occurs when the device is not `cuda:0`**. 
The device information is as follows: 
![image](https://github.com/user-attachments/assets/d28725e4-4147-455b-bf6e-1bac94542608)

**Comment by SonSang** [comment]
Yes, I confirmed that I get the same error when I use other gpu than `cuda:0` on my machine. However, in my case, it goes away when I use following command:
`CUDA_VISIBLE_DEVICES=1 python …py`
(Assuming using `cuda:1`)

Can you tell me how you used the command?

**Comment by Foreverinne** [comment]
Thanks for your quickly reply!
I successfully solved this problem by using the command you gave: `CUDA_VISIBLE_DEVICES=1 python ...py`. The reason for the error was that I did not change the value of device in `{}.yaml` from `cuda:1` to `cuda`. 
Thanks for your help！
