### ISSUE TITLE
Question about coordinate system 

### ISSUE THREAD

**Issue by yiming-cc** [SonSang/dmesh#15]
Thanks for the wonderful work! Can you help me figure out the world coordinate and camera coordinate used in code? Thanks!

**Comment by SonSang** [comment]
Hi, thank you for your interest, and sorry for the late reply.

Currently, we use model-view matrix and projection matrix defined in [this](https://github.com/SonSang/dmesh/blob/8a76623aa9d8b0cc9673061eb0eef7de36b3d795/exp/utils/mv.py#L35) function. We call the function at the initialization stage of an experiment, as shown [here](https://github.com/SonSang/dmesh/blob/8a76623aa9d8b0cc9673061eb0eef7de36b3d795/exp/3_mv_recon.py#L656).

We use those matrices to transform the world coordinates into the camera or other coordinates.
