### ISSUE TITLE
Great!  This is what I urgently desire！

### ISSUE THREAD

**Issue by yuedajiong** [SonSang/dmesh#2]
Awesome! 
Next, study carefully...

**Comment by SonSang** [comment]
Thanks for your interest! :)

**Comment by LaFeuilleMorte** [comment]
> Awesome! Next, study carefully...

Hi, bro. Met you again. Do you research in 3D representation/ 3D generative models?

**Comment by yuedajiong** [comment]
@LaFeuilleMorte 
Yes
You can see my progressing on my github.
