### ISSUE TITLE
Install guide for Windows!

### ISSUE THREAD

**Issue by MrForExample** [SonSang/dmesh#3]
### Assume you already initialize your conda environment, and cloned this project

In windows, use `cmake --build .` instead of `make`

When build **[[DMeshRenderer](https://github.com/SonSang/dmesh_renderer)](https://github.com/SonSang/dmesh_renderer)**, if you encounter error:

- `fatal error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory`

Solution:

1. **Installing Vcpkg:**
    
    ```bash
    git clone https://github.com/microsoft/vcpkg
    cd vcpkg
    .\bootstrap-vcpkg.bat
    # Add environment variable: VCPKG_ROOT = "Your vcpkg directory" e.g. C:\Users\reall\Softwares\vcpkg
    # Add same path to Path environment variable
    ```
    
2. Install GLM: `vcpkg install glm` 
    
    Copy `glm` folder from `vcpkg\packages\glm_x64-windows\include` to your conda environment’s `include` folder
    

When build & install **[[OneTBB](https://github.com/oneapi-src/oneTBB)](https://github.com/oneapi-src/oneTBB)**  if you encounter error:

- `CMake Error at src/tbb/cmake_install.cmake:51 (file): 
file INSTALL cannot find "C:/Users/reall/Softwares/Miniconda/envs/AI3D_Exp/_Projects/dmesh/external/oneTBB/build/msvc_19.39_cxx_64_md_release/tbb12.dll": File exists.`

Solution:

- https://github.com/oneapi-src/oneTBB/issues/708#issuecomment-1015170539
    
    ```bash
    cd external/oneTBB
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_PREFIX=../install -DTBB_TEST=OFF ..
    cmake --build . --config release
    cmake --install . --config release
    ```
    

Install [[CGAL 5.6.1 - Manual: Using CGAL on Windows (with Visual C++)](https://doc.cgal.org/latest/Manual/windows.html#install-from-source)](https://doc.cgal.org/latest/Manual/windows.html#install-from-source)

When build **cgal_wrapper**, if you encounter error:

- `dmesh\external\cgal\Installation\include\CGAL\config.h(111,10): error C1083: Cannot open include file: 'boost/config.hpp': No such file or directory`

Solution:

- In `dmesh\cgal_wrapper\CMakeLists.txt` add additional line after `target_include_directories()` to `include_directories("boost folder’s parent folder, e.g. C:/Users/reall/Softwares/boost_1_85_0")`

When build **DMesh (**running `pip install -e .` in dmesh directory**)**, If you encounter error

1. `LINK : fatal error LNK1181: cannot open input file 'cgal wrapper.lib’`
    
    Solution:
    
    - Move `cgal wrapper.lib` from `dmesh\cgal_wrapper\Debug\` under `dmesh\cgal_wrapper`
    - Or move it to other include library path, check `dmesh\setup.py`
2. `LINK : fatal error LNK1181: cannot open input file 'gmp.lib’` or `'mpfr.lib’`
    
    Solution: 
    
    - Move `gmp.lib` or `'mpfr.lib’` from `vcpkg\packages\gmp_x64-windows\lib` or `vcpkg\packages\mpfr_x64-windows\lib` to your conda environment’s `libs` folder
    

 @SonSang 
### Awesome work based on a great idea. But a little suggestion, if you want people to use your work and create more useful tools or research papers with it, then you definitely want to put in some effort to make it easy to install. This project is easily one of the hardest project I ever installed.
  Cheers, have a good day :)

**Comment by SonSang** [comment]
Thanks for your effort in writing the installation guide for Windows, I really appreciate it.
Unfortunately, me and all of my collaborators worked in Linux environment, we did not have a chance to test our project in Windows environment.
In the Readme, we will specify that the installation guides are for Linux environment, and direct Window users to this guide.
Sorry for your inconvenience, and thank you again for writing this guide.
