### ISSUE TITLE
How to control the number of face of the resulting mesh?

### ISSUE THREAD

**Issue by YuCrazing** [SonSang/dmesh#4]
In the config file, for example, `exp/config/exp_3/thingi32/252119.yaml`. I can not find a parameter to control the final number of faces. It seems that the only relevant parameter is `refine`. However, the parameter `refine` can not directory control the face number either.

**Comment by SonSang** [comment]
Hi, for now, we do not have functionality to directly control the final number of faces.
We can control the coefficient for the weight regularization to reduce the number of faces.
However, it does not mean that we can specify the number of faces that we want, and optimize our mesh accordingly.
