### ISSUE TITLE
Multi-view image reconstruction

### ISSUE THREAD

**Issue by Yubel426** [SonSang/dmesh#5]
Great job! I'm new to this field, and I want to know if it's possible to reconstruct from an RGB image?

**Comment by SonSang** [comment]
Hi, sorry for the late reply!
Right now we implemented our code to encode vertex wise RGB value and use barycentric interpolation for rendering. But we did not test it officially yet. It is one of our future works at this stage.

**Comment by Yubel426** [comment]
Thank you for your reply.
