### ISSUE TITLE
Problem about multi-view reconstruction

### ISSUE THREAD

**Issue by lizhiqi49** [SonSang/dmesh#8]
In section C.3.1 of the paper you mentioned that the implementation of F_A (the first renderer) does not produce visibility-related gradients (near face edges). It's hard for me to understand the term "visibility-related gradients", can you figure me out what it means in your method?

**Comment by SonSang** [comment]
Hi, the visibility-related gradient is the gradient related to occlusion. For example, when a vertex incident to an edge or a face moves, the edge and the face can also change and it can occlude (or reveal) other faces behind them. This occlusion is naturally discrete, so previous methods bypass this problem with different techniques (e.g. nvdiffrast uses anti-aliasing). We use two renderers, one of which uses this nvdiffrast to produce the visibility-related gradients.

**Comment by lizhiqi49** [comment]
I understand, thanks for your nice explaination!
